"""
Architectural Role: Core Domain Models & Schema Definitions.
This module defines the essential data structures (dataclasses and enums) used 
throughout the system to ensure type safety and consistency across agents, 
orchestrators, and the TUI.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List, Dict


class ExecutionMode(Enum):
    """
    Function: Defines how multiple agents collaborate.
    Why: PARALLEL is optimized for speed/independent tasks, while DISCUSSION 
    is optimized for quality and consensus through iterative refinement.
    """
    PARALLEL = "parallel"
    DISCUSSION = "discussion"


class AgentStatus(Enum):
    """Reflects the current activity state of an orchestrator agent."""
    IDLE = "IDLE"
    THINKING = "THINKING 🧠"
    ACTING = "ACTING ⚙️"
    VERIFYING = "VERIFYING 🔍"
    SUCCESS = "SUCCESS ✔"
    FAILURE = "FAILURE ✖"
    WAITING = "WAITING ⌛"


@dataclass
class AgentState:
    """Holds the ephemeral state for a single agent in the TUI view."""
    name: str
    status: AgentStatus = AgentStatus.IDLE
    attempt: int = 0
    max_retries: int = 0
    last_action: str = ""
    logs: List[str] = field(default_factory=list)
    diff: Optional[str] = None


@dataclass
class DeploymentUnit:
    """Represents a single agent deployment (Persona + LLM Engine)."""
    persona: str
    engine: str


@dataclass
class AgentResult:
    """Holds the raw output and execution metrics of an agent's task."""
    agent_name: str
    ok: bool
    stdout: str
    stderr: str
    returncode: int
    duration_ms: int
    tokens: int = 0
    truncated: bool = False


@dataclass
class ConsensusResult:
    """Represents the outcome of a multi-agent agreement phase."""
    status: str
    shared_points: list[str] = field(default_factory=list)
    open_issues: list[str] = field(default_factory=list)
    recommended_final: str = ""


@dataclass
class TurnResult:
    """Tracks a single round of interaction in the Discussion/Relay mode."""
    round_num: int
    gemini_answer: str = ""
    codex_answer: str = ""
    gemini_review: str = ""
    codex_review: str = ""


@dataclass
class SynthesisProposal:
    """
    Function: Represents a unified solution generated by the Synthesis Engine.
    Why: It consolidates multiple agent proposals, identifies resolved 
    conflicts, and provides a technical rationale for the chosen path.
    """
    proposal_id: str
    agents_involved: List[str]
    synthesized_diff: str
    conflicts: List[str] = field(default_factory=list)
    rationale: str = ""


@dataclass
class SessionManifest:
    """
    Function: The complete record of a session's parameters and final state.
    Why: This is the primary JSON artifact used to restore sessions and provide 
    audit trails for AI-generated code changes.
    """
    session_id: str
    timestamp: float
    user_prompt: str
    deployment_units: list[dict]
    git_hash: Optional[str] = None
    os_info: Optional[str] = None
    env_vars: dict = field(default_factory=dict)
    status: str = "PENDING"
    duration_ms: int = 0
    total_tokens: int = 0
    artifacts_path: str = ""
    checkpoint_name: Optional[str] = None
    workspace: str = "Unknown"


@dataclass
class RegistryEntry:
    """Lightweight entry for the global session index."""
    session_id: str
    timestamp: float
    user_prompt: str
    status: str
    artifacts_path: str
    workspace: str = "Unknown"
    checkpoint_name: Optional[str] = None


# Why: Standardized system prompts for different roles ensure that agents 
# maintain a consistent "voice" and prioritize the right technical trade-offs.
DEFAULT_AGENT_PERSONAS = {
    "architect": "You are a super architect.",
    "engineer": "You are a Senior Software Engineer. Your goal is to write robust, efficient, and idiomatic code to implement features and solve problems pragmatically. IMPORTANT: You MUST strictly use the JSON tool format for every action.",
    "reviewer": "You are a Strict Senior Code Reviewer. Your goal is to audit code for bugs, edge cases, logic flaws, and adherence to best practices. Suggest concrete improvements. IMPORTANT: You MUST strictly use the JSON tool format for every action.",
    "debugger": "You are an Expert Debugger. Your priority is to identify root causes of failures, trace execution paths, and provide precise, surgical fixes for complex bugs. IMPORTANT: You MUST strictly use the JSON tool format for every action.",
    "uiux": "You are a UI/UX Expert. Your priority is to ensure intuitive interfaces, accessibility, responsive design, and an excellent user experience. Focus on usability and aesthetics. IMPORTANT: You MUST strictly use the JSON tool format for every action.",
    "security": "You are a Cyber Security Expert. Your priority is safety, input validation, preventing resource leaks, and defending against injection attacks. Be paranoid about edge cases. IMPORTANT: You MUST strictly use the JSON tool format for every action."
}

AGENT_PERSONAS = DEFAULT_AGENT_PERSONAS.copy()
